### ISSUE TITLE
direnv dependency

### ISSUE THREAD

**Issue by dkhopade** [tanzu-end-to-end/tap-gitops-workshop#3]
Hello Team,

Its really minor but could save some time. There's **direnv** (https://github.com/tanzu-end-to-end/tap-gitops-workshop/blob/fa4afbbf49f76d2e2faf87a7ed54f15f98585bec/Stage-1-Base-Install.md?plain=1#L13) dependency thats mentioned in stage 1 but not on prereqs.

**Comment by cpage-pivotal** [comment]
Thank you for the PR

**Comment by dkhopade** [comment]
Thanks Corby for merging it.
